"""renames address

Revision ID: 325d060aa857
Revises: 29477a71c301
Create Date: 2024-10-01 13:35:29.246428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '325d060aa857'
down_revision = '29477a71c301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###
